# 欲修改規則
# 請將設定檔前2行註釋取消後
# 將同資料夾下的 .stylelintrc.json-example
# 重新命名為 .stylelintrc.json
# 編輯 .stylelintrc.json


# 規則請參考以下網站
# stylelint config standard
# https://github.com/stylelint/stylelint-config-standard

# ====================#
#      以下為設定檔     #
# ====================#

# extends:
#   - ./.stylelintrc.json
